💚  Add test report action

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -7,4 +7,13 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Build the stack
-        run: docker build .
+        run: docker-compose build
+      - name: Export test results
+        run: docker-compose up && docker-compose down
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: JEST Tests # Name of the check run which will be created
+          path: test_results/**/*.xml # Path to test results
+          reporter: jest-junit # Format of test results
